// swift-tools-version: 5.9
// SpendTracker.xcodeproj is generated by Xcode
// This Package.swift is provided for reference only

// To open in Xcode:
// 1. Double-click SpendTracker.xcodeproj
// 2. OR run: open SpendTracker.xcodeproj

// Dependencies used:
// - Charts (Apple's Swift Charts - built into iOS 16+)
// - CoreData (built-in)
// - UserNotifications (built-in)
// - PDFKit (built-in)
// - MessageUI (built-in)
